name: Build and Push Educare Docker Images

on:
  push:
    tags: 
      - 'd*'

env:
  IMAGE_NAME: greatideasgh/educarehigh

permissions:
  contents: write
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  BuildDocker:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4.2
        with:
          path: .

      - name: Set version
        run: echo "SimpleVersion=$(nbgv get-version -v SimpleVersion)" >> $GITHUB_ENV     
      
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: docker.io/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=true    

      - name: Build Docker image
        run: |
          docker build --file src/Web/Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ env.SimpleVersion }} .
