name: Release Workflow

on:
  push:
    tags: 
      - 'v*'
    # branches:
    #   - master
  # milestone:
  #   types: [closed]


permissions:
  contents: write
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Release 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Release Notes
        id: release_notes
        run: |
          # Use Git log to fetch commit messages since the last tag
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          previous_tag=$(git describe --tags --abbrev=0)
          current_tag=$(git describe --tags)
          release_notes=$(git log --pretty=format:"%s" $previous_tag..$current_tag)
          echo "::set-output name=notes::$release_notes"

      - name: Build
        run: echo "${{ github.sha }}" > Release.txt
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false
