name: Release Workflow

on:
  push:
    tags: 
      - 'v*'
    # branches:
    #   - master
  # milestone:
  #   types: [closed]


permissions:
  contents: write
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Release 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: "ergebnis/.github/actions/github/release/create@1.8.0"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build
        run: echo "${{ github.sha }}" > Release.txt
      
      - name: Add Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
