name: Release Workflow

on:
  push:
    tags: 
      - 'v*'
    # branches:
    #   - master
  # milestone:
  #   types: [closed]


permissions:
  contents: write
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  release:
    name: Release 
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Drafter
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
        
      # - name: Create Release
      #   uses: "geraldmaale/.github/actions/github/release/create@v1.0.0"
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
